/**
 * Données partagées : établissements secondaires du Mfoundi (Yaoundé) utilisés
 * par seed-mfoundi-schools.mjs, seed-mfoundi-schools-national.mjs et
 * seed-mfoundi-resources.mjs.
 *
 * Source : ecole-secondaire-mfoundi.pdf, "Liste complète des établissements
 * secondaires du Mfoundi" (DDES Mfoundi, dres-ce.jimdofree.com), colonnes
 * [Nom | Arrondissement | Création | Type | Ordre | Système].
 *
 * languageSystem : seul l'établissement explicitement marqué "Bilingue" dans
 * la colonne Système du PDF reçoit BILINGUAL ; tous les autres établissements
 * du Mfoundi (division de Yaoundé, zone francophone, aucune mention
 * "Anglophone" dans la source) reçoivent FRANCOPHONE par défaut.
 *
 * cycle : le document ne couvre que l'enseignement secondaire -> SECONDARY
 * pour toutes les entrées.
 *
 * Certains établissements apparaissent deux fois dans la source (une ligne
 * "Général", une ligne "Technique" pour le même nom) : ce sont deux entrées
 * Scolive distinctes (deux filières = deux écoles), désambiguïsées par
 * slug dans le script de seed. La ligne "ENIEG B" (Type = Normal, école
 * normale d'instituteurs) est hors périmètre et n'apparaît pas ici. Les deux
 * lignes strictement identiques ("Collège des Sciences et Techniques
 * Industrielles", Yaoundé 6, 1978, Technique, Laïc) ont été dédupliquées.
 */

export const MFOUNDI_SCHOOLS = [
  {
    name: "Academic College of Excellence",
    arrondissement: "Yaoundé 1",
    foundedYear: 2011,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Amasia Mahamain Bilingual Secondary School",
    arrondissement: "Yaoundé 4",
    foundedYear: 2001,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "BILINGUAL",
  },
  {
    name: "Ayungha Bilingual College",
    arrondissement: "Yaoundé 5",
    foundedYear: 2000,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "BILINGUAL",
  },
  {
    name: "Ayungha Bilingual College",
    arrondissement: "Yaoundé 5",
    foundedYear: 2000,
    schoolType: "TECHNICAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Baptist Secondary School Yaoundé",
    arrondissement: null,
    foundedYear: 2008,
    schoolType: "GENERAL",
    ownership: "Protestant",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Biangoro Institute of Science, Technology and Arts (BISTA)",
    arrondissement: null,
    foundedYear: null,
    schoolType: "GENERAL",
    ownership: "Islamique",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Bilik-City Bilingual Complex",
    arrondissement: "Yaoundé 1",
    foundedYear: 2012,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "BILINGUAL",
  },
  {
    name: "Bilingual African College of Techniques (BACT)",
    arrondissement: "Yaoundé 6",
    foundedYear: 2010,
    schoolType: "TECHNICAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Bodio Bilingual Complex",
    arrondissement: "Yaoundé 5",
    foundedYear: 2010,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },

  {
    name: "Cameroon School of Excellence",
    arrondissement: "Yaoundé 5",
    foundedYear: 2004,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Centre Educatif d'Ekoudou Bastos (CEEB)",
    arrondissement: "Yaoundé 1",
    foundedYear: null,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Centre Educatif le Bon Berger",
    arrondissement: "Yaoundé 4",
    foundedYear: 2001,
    schoolType: "TECHNICAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Centre Educatif Meyon Meyeme",
    arrondissement: "Yaoundé 7",
    foundedYear: 1998,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "CES de Nyom",
    arrondissement: "Yaoundé 1",
    foundedYear: 2013,
    schoolType: "GENERAL",
    ownership: null,
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "CETI Benigna",
    arrondissement: "Yaoundé 1",
    foundedYear: 1969,
    schoolType: "TECHNICAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "CETI Jeanne Alegué",
    arrondissement: null,
    foundedYear: 1968,
    schoolType: "TECHNICAL",
    ownership: "Catholique",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "CETI Jeanne Alegue Messi",
    arrondissement: "Yaoundé 4",
    foundedYear: 2010,
    schoolType: "TECHNICAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "CETI Notre Dame des Victoires",
    arrondissement: "Yaoundé 5",
    foundedYear: 1966,
    schoolType: "TECHNICAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "CETI Sacré Coeur de Mokolo",
    arrondissement: "Yaoundé 1",
    foundedYear: 1965,
    schoolType: "TECHNICAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "CETI Sacré-Coeur de Mokolo",
    arrondissement: "Yaoundé 2",
    foundedYear: 1965,
    schoolType: "TECHNICAL",
    ownership: "Catholique",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "CETIC de Ngoa-Ekellé",
    arrondissement: "Yaoundé 3",
    foundedYear: 1954,
    schoolType: "TECHNICAL",
    ownership: null,
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "CETIF Benigna",
    arrondissement: "Yaoundé 1",
    foundedYear: 1966,
    schoolType: "TECHNICAL",
    ownership: "Catholique",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "CETIF de Ngoa Ekelle Yaounde",
    arrondissement: "Yaoundé 3",
    foundedYear: 1958,
    schoolType: "TECHNICAL",
    ownership: null,
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "CETIG Bénédictin du Mt Febé",
    arrondissement: "Yaoundé",
    foundedYear: 1988,
    schoolType: "GENERAL",
    ownership: "Catholique",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Chuo Bilingual Comprehensive College (CBCC)",
    arrondissement: "Yaoundé 2",
    foundedYear: 2007,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "BILINGUAL",
  },
  {
    name: "City Bilingual Academy",
    arrondissement: "Yaoundé 6",
    foundedYear: 1977,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "BILINGUAL",
  },
  {
    name: 'Collège "Les Coccinelles"',
    arrondissement: "Yaoundé 2",
    foundedYear: 2008,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège Adventiste de Yaoundé-Nlongkak",
    arrondissement: null,
    foundedYear: 1992,
    schoolType: "GENERAL",
    ownership: "Adventiste",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: 'Collège Anglo-Saxon "Pi and Ju Plus"',
    arrondissement: "Yaoundé 4",
    foundedYear: 2003,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège B. Olive",
    arrondissement: "Yaoundé 6",
    foundedYear: 2010,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "BILINGUAL",
  },
  {
    name: "Collège Benigna d'Etoudi",
    arrondissement: null,
    foundedYear: 1969,
    schoolType: "GENERAL",
    ownership: "Catholique",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège Benisuza",
    arrondissement: "Yaoundé - Messamendongo",
    foundedYear: 2005,
    schoolType: "GENERAL",
    ownership: "Catholique",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège Bénoit XVI",
    arrondissement: "Yaoundé 3",
    foundedYear: 2009,
    schoolType: "GENERAL",
    ownership: "Catholique",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège Bilingue Bethelehem Legrand",
    arrondissement: "Yaoundé 2",
    foundedYear: 2008,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "BILINGUAL",
  },
  {
    name: "Collège Bilingue Golden Institute",
    arrondissement: "Yaoundé 5",
    foundedYear: 2010,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège Bilingue International la Fierte",
    arrondissement: "Yaoundé 4",
    foundedYear: 2013,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège Bilingue Jeunesse Lumiere",
    arrondissement: "Yaoundé 4",
    foundedYear: 2005,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège Bilingue la Gloire",
    arrondissement: null,
    foundedYear: 2010,
    schoolType: "GENERAL",
    ownership: "Catholique",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège Bilingue les Agneaux",
    arrondissement: "Yaoundé 7",
    foundedYear: 2008,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "BILINGUAL",
  },
  {
    name: "Collège Bilingue les Anges",
    arrondissement: "Yaoundé 4",
    foundedYear: null,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège Bilingue les Oisillons",
    arrondissement: "Yaoundé 6",
    foundedYear: 2010,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "BILINGUAL",
  },
  {
    name: "Collège Bilingue Lincoln",
    arrondissement: "Yaoundé 2",
    foundedYear: 2011,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "BILINGUAL",
  },
  {
    name: "Collège Bilingue Prive Laic William Booth",
    arrondissement: "Yaoundé 1",
    foundedYear: 2006,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège Bilingue Seat of Wisdom",
    arrondissement: "Yaoundé 1",
    foundedYear: 2004,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "BILINGUAL",
  },
  {
    name: "Collège Bilingue Shakespeare",
    arrondissement: "Yaoundé 4",
    foundedYear: 1996,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège Bilingue Sibafo",
    arrondissement: "Yaoundé 1",
    foundedYear: 2008,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège Bilingue Yondo",
    arrondissement: "Yaoundé 4",
    foundedYear: 2007,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège Braunschweig (COLBRA)",
    arrondissement: "Yaoundé 4",
    foundedYear: 2009,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège Catholique Deo Gratias Emana",
    arrondissement: null,
    foundedYear: 2010,
    schoolType: "GENERAL",
    ownership: "Catholique",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège de la Mefou",
    arrondissement: "Yaoundé 4",
    foundedYear: 1968,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège de la Paix",
    arrondissement: "Yaoundé 7",
    foundedYear: 2007,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège de la Renovation",
    arrondissement: "Yaoundé 6",
    foundedYear: 1964,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège de la Retraite",
    arrondissement: "Yaoundé - Centre-ville",
    foundedYear: 1951,
    schoolType: "GENERAL",
    ownership: "Catholique",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège de l'Unite",
    arrondissement: "Yaoundé 1",
    foundedYear: 1978,
    schoolType: "TECHNICAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège d'Enseignement Technique Ekani Eyenga",
    arrondissement: "Yaoundé 7",
    foundedYear: 2002,
    schoolType: "TECHNICAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège d'Enseignement Technique et General de l'Unite",
    arrondissement: "Yaoundé 1",
    foundedYear: 1989,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège d'Enseignement Technique Industriel Feminin",
    arrondissement: "Yaoundé 5",
    foundedYear: 2009,
    schoolType: "TECHNICAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège des Sciences et Techniques Industrielles",
    arrondissement: "Yaoundé 6",
    foundedYear: 1978,
    schoolType: "TECHNICAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège Diderot",
    arrondissement: "Yaoundé 3",
    foundedYear: 2009,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège Ebanda",
    arrondissement: "Yaoundé 6",
    foundedYear: 1991,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège Elohim",
    arrondissement: "Yaoundé 2",
    foundedYear: 2011,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège Fadimatou Hadja",
    arrondissement: "Yaoundé 5",
    foundedYear: 1991,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège Fadimatou Hadja",
    arrondissement: "Yaoundé 5",
    foundedYear: 1991,
    schoolType: "TECHNICAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège Fido",
    arrondissement: "Yaoundé 1",
    foundedYear: 2008,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège Foche",
    arrondissement: "Yaoundé 5",
    foundedYear: 2009,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège Frantz Fanon",
    arrondissement: "Yaoundé 4",
    foundedYear: 2006,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège Fusee (Fondation Universelle Stella Engama)",
    arrondissement: "Yaoundé 6",
    foundedYear: 1993,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège FX Vogt",
    arrondissement: "Yaoundé 3",
    foundedYear: 1947,
    schoolType: "GENERAL",
    ownership: "Catholique",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège International Bilingue Dada et Fils",
    arrondissement: "Yaoundé 4",
    foundedYear: 2012,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège International de Reference la Farandole",
    arrondissement: "Yaoundé 4",
    foundedYear: null,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège Iplex Education",
    arrondissement: "Yaoundé 1",
    foundedYear: 2002,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège Jean Tabi",
    arrondissement: "Yaoundé 1",
    foundedYear: 1961,
    schoolType: "GENERAL",
    ownership: "Catholique",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège Jesus-Marie",
    arrondissement: null,
    foundedYear: 2010,
    schoolType: "GENERAL",
    ownership: "Catholique",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège Jules Ferry",
    arrondissement: "Yaoundé 6",
    foundedYear: 2008,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },

  {
    name: "Collège Kiatabala",
    arrondissement: "Yaoundé 7",
    foundedYear: 1998,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège la Dignite",
    arrondissement: "Yaoundé 5",
    foundedYear: 2009,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège la Grace Tchetgna",
    arrondissement: "Yaoundé 3",
    foundedYear: 2010,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège le Samaritain-Yaounde",
    arrondissement: "Yaoundé 7",
    foundedYear: 2010,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège les Futurs Boss",
    arrondissement: "Yaoundé 3",
    foundedYear: 2007,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège Maison Dola",
    arrondissement: "Yaoundé 4",
    foundedYear: 2009,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège Marie Albert II",
    arrondissement: "Yaoundé 4",
    foundedYear: 2005,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège Markesso",
    arrondissement: "Yaoundé 6",
    foundedYear: 2003,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège Mathieu et Claire",
    arrondissement: "Yaoundé 5",
    foundedYear: 2004,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège Mgr Jean Zoa",
    arrondissement: null,
    foundedYear: 2008,
    schoolType: "GENERAL",
    ownership: "Catholique",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège Notre-Dame des Victoires",
    arrondissement: "Yaoundé - Mvog Ada",
    foundedYear: 1958,
    schoolType: "GENERAL",
    ownership: "Catholique",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège Oliveraie de Nyom",
    arrondissement: "Yaoundé 1",
    foundedYear: 2009,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège Omgba Ndongo",
    arrondissement: "Yaoundé 1",
    foundedYear: 2008,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège Peniel",
    arrondissement: "Yaoundé 1",
    foundedYear: 2008,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège Polyvalent Bilingue les Aiglons",
    arrondissement: "Yaoundé 6",
    foundedYear: 2006,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège Polyvalent Bilingue les Aiglons",
    arrondissement: "Yaoundé 6",
    foundedYear: 2001,
    schoolType: "TECHNICAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège Polyvalent la Mutuelle Communautaire de Developpement",
    arrondissement: "Yaoundé 6",
    foundedYear: 2011,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège Polyvalent la Perle Plus",
    arrondissement: "Yaoundé 7",
    foundedYear: null,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège Polyvalent les Laureats",
    arrondissement: "Yaoundé 4",
    foundedYear: 2009,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège Polyvalent Pere Matthieu",
    arrondissement: "Yaoundé 4",
    foundedYear: 2011,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège Polyvalent Saint Augustin",
    arrondissement: "Yaoundé 5",
    foundedYear: 2006,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège Polyvalent Saint Augustin",
    arrondissement: "Yaoundé 5",
    foundedYear: 2006,
    schoolType: "TECHNICAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège Polyvalent Saint Pierre",
    arrondissement: "Yaoundé 4",
    foundedYear: 2011,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège Polyvalent Sainte Mere",
    arrondissement: "Yaoundé 6",
    foundedYear: 2013,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège Prive Bilingue les Mignons",
    arrondissement: "Yaoundé 4",
    foundedYear: 2002,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège Prive Bilingue les Pierres Precieuses",
    arrondissement: "Yaoundé 1",
    foundedYear: 2008,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège Prive Diderot",
    arrondissement: "Yaoundé 3",
    foundedYear: 2009,
    schoolType: "TECHNICAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège Prive du Succes",
    arrondissement: "Yaoundé 5",
    foundedYear: 2008,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège Prive Eloundou Marguerite",
    arrondissement: "Yaoundé 4",
    foundedYear: 2012,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège Prive Jardin d'Eden",
    arrondissement: "Yaoundé 4",
    foundedYear: 2007,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: 'Collège Prive Laïc "Excellence Plus" de Yaounde',
    arrondissement: "Yaoundé 7",
    foundedYear: null,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège Prive Laic Atangana Essomba",
    arrondissement: "Yaoundé 4",
    foundedYear: 2001,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège Prive Laïc Atangana Fouda Albert",
    arrondissement: "Yaoundé 3",
    foundedYear: 2010,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: 'Collège Prive Laïc Bilingue "les Bambis"',
    arrondissement: "Yaoundé 3",
    foundedYear: 2000,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "BILINGUAL",
  },

  {
    name: "Collège Prive Laic Centre Socio Educatif Bilingue David",
    arrondissement: "Yaoundé 3",
    foundedYear: 2007,
    schoolType: "TECHNICAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège Prive Laïc Charles Mbakop",
    arrondissement: "Yaoundé 1",
    foundedYear: null,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège Prive Laic Complexe Bilingue Yondo",
    arrondissement: "Yaoundé 4",
    foundedYear: 2007,
    schoolType: "TECHNICAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège Prive Laic de l'Esperance",
    arrondissement: "Yaoundé 5",
    foundedYear: 1992,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège Prive Laic de l'Esperance (COPES)",
    arrondissement: "Yaoundé 5",
    foundedYear: 1992,
    schoolType: "TECHNICAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège Prive Laïc Dja'Ankeu",
    arrondissement: "Yaoundé 5",
    foundedYear: 2004,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège Prive Laic Dolta",
    arrondissement: "Yaoundé 4",
    foundedYear: 2010,
    schoolType: "TECHNICAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège Prive Laïc Dolta",
    arrondissement: "Yaoundé 4",
    foundedYear: 2010,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège Prive Laic du Mont Valerien",
    arrondissement: "Yaoundé 4",
    foundedYear: 2000,
    schoolType: "TECHNICAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège Prive Laic du Savoir",
    arrondissement: "Yaoundé 6",
    foundedYear: 2000,
    schoolType: "TECHNICAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège Prive Laïc du Savoir",
    arrondissement: "Yaoundé 6",
    foundedYear: 2000,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège Prive Laïc Effa Gaston (COPLEG)",
    arrondissement: "Yaoundé 4",
    foundedYear: 1999,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège Prive Laic Enfant d'Afrique",
    arrondissement: "Yaoundé 1",
    foundedYear: 2007,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège Prive Laic Fapo",
    arrondissement: "Yaoundé 1",
    foundedYear: 2001,
    schoolType: "TECHNICAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège Prive Laïc Fapo",
    arrondissement: "Yaoundé 1",
    foundedYear: 1996,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège Prive Laic Fleming",
    arrondissement: "Yaoundé 6",
    foundedYear: 1994,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège Prive Laic Frantz",
    arrondissement: "Yaoundé 4",
    foundedYear: 1988,
    schoolType: "TECHNICAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège Prive Laic Golden Institute",
    arrondissement: "Yaoundé 5",
    foundedYear: 2012,
    schoolType: "TECHNICAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège Prive Laic Institut Bilingue Baudelaire (IBB)",
    arrondissement: "Yaoundé 6",
    foundedYear: 2004,
    schoolType: "TECHNICAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège Prive Laic Institut Jean Body Zibi",
    arrondissement: "Yaoundé 1",
    foundedYear: 2001,
    schoolType: "TECHNICAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège Prive Laïc International Pythagore",
    arrondissement: "Yaoundé 5",
    foundedYear: 2011,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège Prive Laic Jean Jaures",
    arrondissement: "Yaoundé 6",
    foundedYear: 2006,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège Prive Laic la Colombe",
    arrondissement: "Yaoundé 3",
    foundedYear: 2007,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège Prive Laic la Dignite",
    arrondissement: "Yaoundé 5",
    foundedYear: 2005,
    schoolType: "TECHNICAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège Prive Laic la Fontaine",
    arrondissement: "Yaoundé 6",
    foundedYear: 2004,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège Prive Laïc la Forge",
    arrondissement: "Yaoundé 1",
    foundedYear: 2002,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège Prive Laïc la Grace",
    arrondissement: "Yaoundé 2",
    foundedYear: 2001,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège Prive Laïc la Victoire",
    arrondissement: "Yaoundé 1",
    foundedYear: 2007,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège Prive Laic Larousse",
    arrondissement: "Yaoundé 5",
    foundedYear: 2002,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège Prive Laic Larousse",
    arrondissement: "Yaoundé 5",
    foundedYear: 2002,
    schoolType: "TECHNICAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: 'Collège Prive Laïc le "Fanion"',
    arrondissement: "Yaoundé 5",
    foundedYear: 2013,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège Prive Laïc l'Emergence",
    arrondissement: "Yaoundé 1",
    foundedYear: 2007,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège Prive Laic les Champs du Lys",
    arrondissement: "Yaoundé 6",
    foundedYear: 2012,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège Prive Laic les Chanterelles",
    arrondissement: "Yaoundé 5",
    foundedYear: 2014,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège Prive Laic les Lilas",
    arrondissement: "Yaoundé 5",
    foundedYear: 2005,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège Prive Laic les Lilas",
    arrondissement: "Yaoundé 5",
    foundedYear: 2005,
    schoolType: "TECHNICAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège Prive Laïc les Pharaons",
    arrondissement: "Yaoundé 4",
    foundedYear: 1998,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège Prive Laic les Sapins",
    arrondissement: "Yaoundé 3",
    foundedYear: 2000,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège Prive Laic les Sapins",
    arrondissement: "Yaoundé 3",
    foundedYear: 2000,
    schoolType: "TECHNICAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège Prive Laïc Marcel Bayardon",
    arrondissement: "Yaoundé 1",
    foundedYear: 2000,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège Prive Laic Marie Albert II (Comal II)",
    arrondissement: "Yaoundé 4",
    foundedYear: 1980,
    schoolType: "TECHNICAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège Prive Laïc Mokala",
    arrondissement: "Yaoundé 6",
    foundedYear: 2006,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège Prive Laïc Montesquieu",
    arrondissement: "Yaoundé 5",
    foundedYear: 1959,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège Prive Laic Mont-Valerien",
    arrondissement: "Yaoundé 4",
    foundedYear: 2004,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège Prive Laïc Mvom-Nnam",
    arrondissement: "Yaoundé 1",
    foundedYear: 2000,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège Prive Laic Notre Dame des Beatitudes",
    arrondissement: "Yaoundé 6",
    foundedYear: 2000,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège Prive Laïc Saint Joseph de Mimboman",
    arrondissement: "Yaoundé 4",
    foundedYear: 2012,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège Prive Laïc Saint-Exupery",
    arrondissement: "Yaoundé 5",
    foundedYear: 2003,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège Prive Laic Sigmund Freud",
    arrondissement: "Yaoundé 6",
    foundedYear: 2004,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège Prive Laic Technique Stella Maris",
    arrondissement: "Yaoundé 7",
    foundedYear: 2008,
    schoolType: "TECHNICAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège Prive Laic Toussaint Antoine",
    arrondissement: "Yaoundé 5",
    foundedYear: 2004,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège Prive Laic Xavier Ebomo",
    arrondissement: "Yaoundé 7",
    foundedYear: 2007,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège Prive Madeleine",
    arrondissement: "Yaoundé 4",
    foundedYear: 1964,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège Prive Moderne de l'Esperance",
    arrondissement: "Yaoundé 6",
    foundedYear: 2003,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège Prive Mongo Beti",
    arrondissement: "Yaoundé 5",
    foundedYear: 1963,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège Protestant des Freres Unis de Yaounde",
    arrondissement: "Yaoundé 4",
    foundedYear: 1998,
    schoolType: "GENERAL",
    ownership: "Protestant",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège Protestant Johnston",
    arrondissement: "Yaoundé 1",
    foundedYear: 1976,
    schoolType: "GENERAL",
    ownership: "Protestant",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège Rosa Parks",
    arrondissement: "Yaoundé 2",
    foundedYear: 2011,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège Sainte Famille",
    arrondissement: "Yaoundé 1",
    foundedYear: 2000,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège Sainte Marguerite",
    arrondissement: "Yaoundé 4",
    foundedYear: 2010,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège Socrate Elandi",
    arrondissement: "Yaoundé 1",
    foundedYear: 2010,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège St Joseph de Messa Mvelé",
    arrondissement: "Awaé",
    foundedYear: 1964,
    schoolType: "GENERAL",
    ownership: "Catholique",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège Technique Industriel",
    arrondissement: "Yaoundé 1",
    foundedYear: 2007,
    schoolType: "TECHNICAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Collège Venus",
    arrondissement: "Yaoundé 7",
    foundedYear: 2008,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Complexe Scolaire Adventiste d'Odza",
    arrondissement: "Yaoundé 6",
    foundedYear: 2000,
    schoolType: "TECHNICAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Complexe Scolaire Adventiste d'Odza",
    arrondissement: null,
    foundedYear: 2000,
    schoolType: "GENERAL",
    ownership: "Adventiste",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Complexe Scolaire Bilingue Metenou",
    arrondissement: "Yaoundé 1",
    foundedYear: 2011,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Complexe Scolaire Eeko de l'Espoir",
    arrondissement: "Yaoundé 4",
    foundedYear: 2013,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Complexe Scolaire Evangelique de Pentecote",
    arrondissement: "Yaoundé 3",
    foundedYear: 2010,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Complexe Scolaire Ile Educative",
    arrondissement: "Yaoundé 1",
    foundedYear: 2000,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },

  {
    name: 'Complexe Scolaire Internationale "la Gaiete"',
    arrondissement: "Yaoundé 1",
    foundedYear: 2003,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: 'Complexe Scolaire les "As" de Mvan',
    arrondissement: "Yaoundé 4",
    foundedYear: 2008,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Complexe Scolaire l'Excellence",
    arrondissement: "Yaoundé 4",
    foundedYear: 2009,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Complexe Scolaire Ornel Bilingual Academy",
    arrondissement: "Yaoundé 1",
    foundedYear: 2008,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Complexe Scolaire Prive Laïc Bilingue Emmaüs (COSBIE)",
    arrondissement: "Yaoundé 6",
    foundedYear: 2003,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Complexe Scolaire Saint Andre",
    arrondissement: "Yaoundé 1",
    foundedYear: 2003,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Complexe Scolaire Thecla",
    arrondissement: "Yaoundé 7",
    foundedYear: 2009,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Complexe Scolaire Yona",
    arrondissement: "Yaoundé 7",
    foundedYear: 2006,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Complexe Scolaire Yona",
    arrondissement: "Yaoundé 7",
    foundedYear: 2006,
    schoolType: "TECHNICAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: 'Cours du Soir "le Progres Social"',
    arrondissement: "Yaoundé 4",
    foundedYear: null,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Cours du Soir Academia",
    arrondissement: "Yaoundé 4",
    foundedYear: 2009,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Cours du Soir Adventiste d'Odza",
    arrondissement: "Yaoundé 4",
    foundedYear: 2005,
    schoolType: "TECHNICAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Cours du Soir Fadimatou Hadja",
    arrondissement: "Yaoundé 5",
    foundedYear: 2013,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "CTI-Nyom",
    arrondissement: "Yaoundé 1",
    foundedYear: 2007,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "English High School (EHS) Yaoundé",
    arrondissement: "Yaoundé 3",
    foundedYear: 2001,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Fondation Scolaire AA",
    arrondissement: "Yaoundé 3",
    foundedYear: 2006,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Fondation Tsoungui",
    arrondissement: "Yaoundé 1",
    foundedYear: 2007,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Franky Secondary School",
    arrondissement: "Yaoundé 6",
    foundedYear: 2011,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Frazati Bilingual College",
    arrondissement: "Yaoundé 3",
    foundedYear: 2011,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "BILINGUAL",
  },
  {
    name: "Gopal Bilingual Secondary School",
    arrondissement: "Yaoundé 1",
    foundedYear: 2010,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "BILINGUAL",
  },
  {
    name: "Groupe Scolaire les Pigeons",
    arrondissement: "Yaoundé 6",
    foundedYear: 2006,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Groupe Scolaire Prive Laic Djonou",
    arrondissement: "Yaoundé 6",
    foundedYear: 2002,
    schoolType: "TECHNICAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Holy Infant High School Yaounde",
    arrondissement: "Yaoundé 6",
    foundedYear: 2008,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Institut Baudelaire Bilingue",
    arrondissement: "Yaoundé 6",
    foundedYear: 2004,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Institut Bilingue d'Etoudi",
    arrondissement: "Yaoundé 1",
    foundedYear: 1991,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "BILINGUAL",
  },
  {
    name: "Institut Bilingue la Confiance",
    arrondissement: "Yaoundé 4",
    foundedYear: 2008,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Institut Bilingue Michelann",
    arrondissement: "Yaoundé 2",
    foundedYear: 2008,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "BILINGUAL",
  },
  {
    name: "Institut Bilingue Toumwa (IBT)",
    arrondissement: "Yaoundé 1",
    foundedYear: 2005,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "BILINGUAL",
  },
  {
    name: "Institut Blaise Pascal",
    arrondissement: "Yaoundé 1",
    foundedYear: 2007,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Institut Central Instic",
    arrondissement: "Yaoundé 4",
    foundedYear: 1994,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Institut de la Reference",
    arrondissement: "Yaoundé 5",
    foundedYear: 2006,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Institut des Sciences Economique et Informatique de Gestion",
    arrondissement: "Yaoundé 6",
    foundedYear: 1996,
    schoolType: "TECHNICAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Institut des Techniques Industrielles d'Etoug-Ebe",
    arrondissement: "Yaoundé 6",
    foundedYear: 1992,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Institut Fotso",
    arrondissement: "Yaoundé 4",
    foundedYear: 2007,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Institut Gazolent",
    arrondissement: "Yaoundé 4",
    foundedYear: 2006,
    schoolType: "TECHNICAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Institut Gazolent d'Ekounou",
    arrondissement: "Yaoundé 4",
    foundedYear: 1984,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },

  {
    name: "Institut Jean Bocchi",
    arrondissement: "Yaoundé 4",
    foundedYear: 2002,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Institut Jean Body Zibi",
    arrondissement: "Yaoundé 2",
    foundedYear: 2001,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Institut le Jourdain BP:25545 YDE",
    arrondissement: "Yaoundé 7",
    foundedYear: 2007,
    schoolType: "TECHNICAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Institut Matamfen",
    arrondissement: "Yaoundé 1",
    foundedYear: 1976,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Institut Matamfen",
    arrondissement: "Yaoundé 1",
    foundedYear: 1976,
    schoolType: "TECHNICAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Institut Mbe",
    arrondissement: "Yaoundé 4",
    foundedYear: 1995,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Institut Mgr Rene Graffin",
    arrondissement: "Yaoundé 7",
    foundedYear: 1995,
    schoolType: "TECHNICAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Institut Moderne Mbassi",
    arrondissement: "Yaoundé 1",
    foundedYear: 2006,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Institut Notre Dame de la Paix",
    arrondissement: "Yaoundé 2",
    foundedYear: 1998,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Institut Pascal",
    arrondissement: "Yaoundé 3",
    foundedYear: 2007,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Institut Petou",
    arrondissement: "Yaoundé 4",
    foundedYear: 2010,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Institut Petou",
    arrondissement: "Yaoundé 4",
    foundedYear: 1993,
    schoolType: "TECHNICAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Institut Polyvalent Bilingue des Nations",
    arrondissement: "Yaoundé 3",
    foundedYear: 2012,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Institut Polyvalent de la Renovation Pedagogique",
    arrondissement: "Yaoundé 3",
    foundedYear: 2003,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Institut Polyvalent du Succes",
    arrondissement: "Yaoundé 4",
    foundedYear: 2011,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Institut Polyvalent Junior",
    arrondissement: "Yaoundé 1",
    foundedYear: 2013,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Institut Polyvalent la Methode",
    arrondissement: "Yaoundé 4",
    foundedYear: 2010,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Institut Polyvalent Nibert (Iponi)",
    arrondissement: "Yaoundé 6",
    foundedYear: 2001,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Institut Polyvalent (Bilingue) Cecile et Gabriel Dipito",
    arrondissement: "Yaoundé 4",
    foundedYear: 2009,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Institut Prive Laic Central (Instic)",
    arrondissement: "Yaoundé 4",
    foundedYear: 2005,
    schoolType: "TECHNICAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Institut Prive Laïc de Developpement Industriel et Commercial (ISDIC)",
    arrondissement: "Yaoundé 1",
    foundedYear: 1992,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Institut Prive Laic Essomba",
    arrondissement: "Yaoundé 5",
    foundedYear: 2003,
    schoolType: "TECHNICAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Institut Prive Laïc Essomba",
    arrondissement: "Yaoundé 5",
    foundedYear: 2003,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Institut Prive Laic Mbe",
    arrondissement: "Yaoundé 4",
    foundedYear: 1994,
    schoolType: "TECHNICAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Institut Prive Laic Mbe (1993)",
    arrondissement: "Yaoundé 4",
    foundedYear: 1993,
    schoolType: "TECHNICAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Institut Prive Laïc Mbeukam",
    arrondissement: "Yaoundé 5",
    foundedYear: 2008,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Institut Prive Laic Paul Momo",
    arrondissement: "Yaoundé 3",
    foundedYear: 2010,
    schoolType: "TECHNICAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Institut Prive Laic Polyvalent Bilingue des Nations",
    arrondissement: "Yaoundé 3",
    foundedYear: 2009,
    schoolType: "TECHNICAL",
    ownership: "Laïc",
    languageSystem: "BILINGUAL",
  },
  {
    name: "Institut Prive Laic Polyvalent Renovation Pedagogique",
    arrondissement: "Yaoundé 3",
    foundedYear: 2003,
    schoolType: "TECHNICAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Institut Prive Laïc Poussi",
    arrondissement: "Yaoundé 7",
    foundedYear: 2004,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: 'Institut Prive Laïc Prive "le Jourdain"',
    arrondissement: "Yaoundé 7",
    foundedYear: 2010,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Institut Prive Laïc Siantou",
    arrondissement: "Yaoundé 5",
    foundedYear: 1987,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Institut Prive Laic Zang Mebenga",
    arrondissement: "Yaoundé 4",
    foundedYear: 2007,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Institut René Graffin",
    arrondissement: null,
    foundedYear: 1991,
    schoolType: "GENERAL",
    ownership: "Catholique",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Institut Rene Philombe",
    arrondissement: "Yaoundé 4",
    foundedYear: 2003,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Institut Samba",
    arrondissement: "Yaoundé 5",
    foundedYear: null,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Institut Samba",
    arrondissement: "Yaoundé 5",
    foundedYear: 1979,
    schoolType: "TECHNICAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Institut Siantou",
    arrondissement: "Yaoundé 4",
    foundedYear: 1987,
    schoolType: "TECHNICAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Institut Taga",
    arrondissement: "Yaoundé 4",
    foundedYear: 2008,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Institut Technique et Professionnel Prive Catholique Don Bosco",
    arrondissement: "Yaoundé 4",
    foundedYear: 2010,
    schoolType: "TECHNICAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Institut Technique Industriel d'Etoug Ebe (I.T.I.E)",
    arrondissement: "Yaoundé 6",
    foundedYear: 1998,
    schoolType: "TECHNICAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Institut Victor Hugo",
    arrondissement: "Yaoundé 3",
    foundedYear: 1990,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "International Bilingual Academy Yaoundé (IBAY)",
    arrondissement: "Yaoundé 7",
    foundedYear: 2008,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },

  {
    name: "ISEIG Enseignements Secondaires",
    arrondissement: "Yaoundé 6",
    foundedYear: 1994,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Kad-Ndap Bilingual Secondary School",
    arrondissement: "Yaoundé 6",
    foundedYear: 2009,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Lycée Bilingue d'Anguissa",
    arrondissement: "Yaoundé 4",
    foundedYear: null,
    schoolType: "GENERAL",
    ownership: "Public",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Lycée Bilingue d'Application",
    arrondissement: "Yaoundé 3",
    foundedYear: 1992,
    schoolType: "GENERAL",
    ownership: "Public",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Lycée Bilingue de Mendong",
    arrondissement: "Yaoundé 6",
    foundedYear: 1990,
    schoolType: "GENERAL",
    ownership: "Public",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Lycée Bilingue de Mimboman",
    arrondissement: "Yaoundé 4",
    foundedYear: 1991,
    schoolType: "GENERAL",
    ownership: "Public",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Lycée Bilingue de Nkolbisson",
    arrondissement: "Yaoundé 7",
    foundedYear: 1991,
    schoolType: "GENERAL",
    ownership: "Public",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Lycée Bilingue de Nkoleton",
    arrondissement: "Yaoundé 1",
    foundedYear: null,
    schoolType: "GENERAL",
    ownership: "Public",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Lycée Bilingue d'Ekounou",
    arrondissement: "Yaoundé 4",
    foundedYear: 2012,
    schoolType: "GENERAL",
    ownership: "Public",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Lycée Bilingue d'Essos",
    arrondissement: "Yaoundé 5",
    foundedYear: 1973,
    schoolType: "GENERAL",
    ownership: "Public",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Lycée Bilingue d'Etoug-Ebé",
    arrondissement: "Yaoundé 6",
    foundedYear: null,
    schoolType: "GENERAL",
    ownership: "Public",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Lycée d'Afan Oyoa",
    arrondissement: "Yaoundé 3",
    foundedYear: 2006,
    schoolType: "GENERAL",
    ownership: "Public",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Lycée d'Ahala",
    arrondissement: "Yaoundé 3",
    foundedYear: 2009,
    schoolType: "GENERAL",
    ownership: "Public",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Lycée de Biyem-Assi",
    arrondissement: "Yaoundé 3",
    foundedYear: 1983,
    schoolType: "GENERAL",
    ownership: "Public",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Lycée de la Cité Verte",
    arrondissement: "Yaoundé 2",
    foundedYear: null,
    schoolType: "GENERAL",
    ownership: "Public",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Lycée de Mballa II",
    arrondissement: "Yaoundé 1",
    foundedYear: 1991,
    schoolType: "GENERAL",
    ownership: "Public",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Lycée de Minkan",
    arrondissement: "Yaoundé 4",
    foundedYear: 1999,
    schoolType: "GENERAL",
    ownership: "Public",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Lycée de Ngoa-Ekellé",
    arrondissement: "Yaoundé 3",
    foundedYear: 2010,
    schoolType: "GENERAL",
    ownership: "Public",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Lycée de Ngousso-Ngoulmekong",
    arrondissement: "Yaoundé 5",
    foundedYear: null,
    schoolType: "GENERAL",
    ownership: "Public",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Lycée de Nkolmesseng",
    arrondissement: "Yaoundé 5",
    foundedYear: 2014,
    schoolType: "GENERAL",
    ownership: "Public",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Lycée de Nkolndongo",
    arrondissement: "Yaoundé 4",
    foundedYear: null,
    schoolType: "GENERAL",
    ownership: "Public",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Lycée de Nkolondom",
    arrondissement: "Yaoundé 1",
    foundedYear: null,
    schoolType: "GENERAL",
    ownership: "Public",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Lycée de Nsam-Efoulan",
    arrondissement: "Yaoundé 3",
    foundedYear: 1987,
    schoolType: "GENERAL",
    ownership: "Public",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Lycée de Tsinga",
    arrondissement: "Yaoundé 2",
    foundedYear: null,
    schoolType: "GENERAL",
    ownership: "Public",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Lycée d'Ekorezok",
    arrondissement: "Yaoundé 7",
    foundedYear: 2010,
    schoolType: "GENERAL",
    ownership: "Public",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Lycée d'Elig-Essono",
    arrondissement: "Yaoundé 1",
    foundedYear: 1991,
    schoolType: "GENERAL",
    ownership: "Public",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Lycée d'Emana",
    arrondissement: "Yaoundé 1",
    foundedYear: 2012,
    schoolType: "GENERAL",
    ownership: "Public",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Lycée d'Odza",
    arrondissement: "Yaoundé 4",
    foundedYear: 2012,
    schoolType: "GENERAL",
    ownership: "Public",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Lycée Général Leclerc",
    arrondissement: "Yaoundé 3",
    foundedYear: 1952,
    schoolType: "GENERAL",
    ownership: "Public",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Lycée Technique Bilingue de Nkolbisson",
    arrondissement: "Yaoundé 7",
    foundedYear: 1992,
    schoolType: "TECHNICAL",
    ownership: "Public",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Lycée Technique Bilingue de Nsam-Efoulan",
    arrondissement: "Yaoundé 3",
    foundedYear: null,
    schoolType: "TECHNICAL",
    ownership: "Public",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Lycée Technique Charles Atangana",
    arrondissement: "Yaoundé 1",
    foundedYear: 1952,
    schoolType: "TECHNICAL",
    ownership: "Public",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Lycée Technique d'Afan Oyoa",
    arrondissement: "Yaoundé 3",
    foundedYear: 2010,
    schoolType: "TECHNICAL",
    ownership: "Public",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Lycée Technique de Nsam-Efoulan",
    arrondissement: "Yaoundé 1",
    foundedYear: 1990,
    schoolType: "TECHNICAL",
    ownership: "Public",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Lycée Technique de Yaoundé II",
    arrondissement: "Yaoundé 2",
    foundedYear: null,
    schoolType: "TECHNICAL",
    ownership: "Public",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Lycée Technique d'Ekounou",
    arrondissement: "Yaoundé 4",
    foundedYear: 1992,
    schoolType: "TECHNICAL",
    ownership: "Public",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Lycée Technique Industriel et Commercial Bilingue",
    arrondissement: "Yaoundé 3",
    foundedYear: 1970,
    schoolType: "TECHNICAL",
    ownership: "Public",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Mario Academic Complex, Mendong",
    arrondissement: "Yaoundé 6",
    foundedYear: null,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Mevick Bilingual Grammar School Etoug-Ebe",
    arrondissement: "Yaoundé 6",
    foundedYear: 1992,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "National Education Service College of Arts and Sciences (NESCA)",
    arrondissement: "Yaoundé 6",
    foundedYear: 2004,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Notre Dame de la Bonne Semence",
    arrondissement: "Yaoundé 5",
    foundedYear: 2010,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Oxford High School",
    arrondissement: "Yaoundé 6",
    foundedYear: 2005,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Quality International School",
    arrondissement: "Yaoundé 6",
    foundedYear: 2008,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Queensway International College",
    arrondissement: "Yaoundé 5",
    foundedYear: 2009,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Roben Memorial Educational Complex",
    arrondissement: "Yaoundé 5",
    foundedYear: 2010,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Séminaire Sainte Thérèse",
    arrondissement: "Yaoundé 3",
    foundedYear: 1962,
    schoolType: "GENERAL",
    ownership: "Catholique",
    languageSystem: "FRANCOPHONE",
  },
  {
    name: "Wecare Secondary School",
    arrondissement: "Yaoundé 3",
    foundedYear: 2011,
    schoolType: "GENERAL",
    ownership: "Laïc",
    languageSystem: "FRANCOPHONE",
  },
].map((entry) => ({ ...entry, cycle: "SECONDARY" }));

export function slugify(text) {
  return text
    .normalize("NFD")
    .replace(/[̀-ͯ]/g, "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

/**
 * Calcule un slug unique par école : les paires "même nom, filière
 * différente" (Général vs Technique) partagent le même nom d'affichage
 * mais doivent obtenir des slugs distincts.
 */
export function withUniqueSlugs(schools) {
  const nameCounts = new Map();
  for (const entry of schools) {
    const key = entry.name.trim().toLowerCase();
    nameCounts.set(key, (nameCounts.get(key) ?? 0) + 1);
  }

  const usedSlugs = new Map();
  return schools.map((entry) => {
    const key = entry.name.trim().toLowerCase();
    const baseSlug = slugify(entry.name);
    const isAmbiguous = (nameCounts.get(key) ?? 0) > 1;
    let slug = isAmbiguous
      ? `${baseSlug}-${entry.schoolType.toLowerCase()}`
      : baseSlug;

    const occurrences = usedSlugs.get(slug) ?? 0;
    if (occurrences > 0) {
      slug = `${slug}-${occurrences + 1}`;
    }
    usedSlugs.set(slug, occurrences + 1);

    return { ...entry, slug };
  });
}
