export const AUTO_GENERATED_EMAIL_DOMAIN = "@noemail.scolive.local";

export function isAutoGeneratedEmail(email: string | null | undefined) {
  return !!email && email.endsWith(AUTO_GENERATED_EMAIL_DOMAIN);
}

export function publicEmailOrNull(email: string | null | undefined) {
  if (!email || isAutoGeneratedEmail(email)) {
    return null;
  }
  return email;
}
