import {
  AUTO_GENERATED_EMAIL_DOMAIN,
  isAutoGeneratedEmail,
  publicEmailOrNull,
} from "../src/common/email.util";

describe("email.util", () => {
  describe("isAutoGeneratedEmail", () => {
    it("returns true for an email ending with the auto-generated domain", () => {
      expect(
        isAutoGeneratedEmail(
          `parent-655112233-ab12cd34${AUTO_GENERATED_EMAIL_DOMAIN}`,
        ),
      ).toBe(true);
    });

    it("returns false for a real email", () => {
      expect(isAutoGeneratedEmail("alice@example.test")).toBe(false);
    });

    it("returns false for null or undefined", () => {
      expect(isAutoGeneratedEmail(null)).toBe(false);
      expect(isAutoGeneratedEmail(undefined)).toBe(false);
    });

    it("returns false for an empty string", () => {
      expect(isAutoGeneratedEmail("")).toBe(false);
    });
  });

  describe("publicEmailOrNull", () => {
    it("returns the email when it is a real address", () => {
      expect(publicEmailOrNull("alice@example.test")).toBe(
        "alice@example.test",
      );
    });

    it("returns null when the email is auto-generated", () => {
      expect(
        publicEmailOrNull(
          `teacher-655112233-ab12cd34${AUTO_GENERATED_EMAIL_DOMAIN}`,
        ),
      ).toBeNull();
    });

    it("returns null when the email is null or undefined", () => {
      expect(publicEmailOrNull(null)).toBeNull();
      expect(publicEmailOrNull(undefined)).toBeNull();
    });
  });
});
