import type { StudentNotesTermSnapshot } from "./student-notes.types";

export const STUDENT_NOTES_DEMO_DATA: StudentNotesTermSnapshot[] = [
  {
    term: "TERM_1",
    label: "1er Trimestre",
    councilLabel:
      "Conseil de classe de 6eme N3 le mardi 9 decembre 2025 a 17:30",
    generatedAtLabel: "Moyennes calculees le jeudi 18 decembre a 09:32",
    generalAverage: {
      student: 16.31,
      class: 16.29,
      min: 12.45,
      max: 18.84,
    },
    subjects: [
      {
        id: "francais",
        subjectLabel: "Francais",
        teachers: ["M. Jamet P.", "Mme Lambert M."],
        coefficient: 1,
        studentAverage: 15.5,
        classAverage: 13.92,
        classMin: 9,
        classMax: 17.33,
        appreciation:
          "Bonne participation francais, Paul travaille avec motivation, continue ainsi.",
        evaluations: [
          {
            id: "fr-1",
            label: "Lecture",
            score: 20,
            maxScore: 20,
            recordedAt: "05/09",
          },
          {
            id: "fr-2",
            label: "Expression ecrite",
            score: 16,
            maxScore: 20,
            recordedAt: "22/10",
          },
          {
            id: "fr-3",
            label: "Grammaire",
            score: 10.5,
            maxScore: 20,
            recordedAt: "18/11",
          },
        ],
      },
      {
        id: "mathematiques",
        subjectLabel: "Mathematiques",
        teachers: ["M. Auberger C.", "M. Jacquier S."],
        coefficient: 1,
        studentAverage: 18.38,
        classAverage: 16.72,
        classMin: 5.25,
        classMax: 20,
        appreciation:
          "Tres bon premier trimestre. Paul est implique a l'ecrit et doit intensifier sa participation a l'oral.",
        evaluations: [
          {
            id: "ma-1",
            label: "Calcul",
            score: 19.5,
            maxScore: 20,
            recordedAt: "12/09",
          },
          {
            id: "ma-2",
            label: "Problemes",
            score: 36.5,
            maxScore: 40,
            recordedAt: "07/10",
            weight: 2,
          },
          {
            id: "ma-3",
            label: "Geometrie",
            score: 17.5,
            maxScore: 20,
            recordedAt: "28/11",
          },
        ],
      },
      {
        id: "histoire",
        subjectLabel: "Histoire-geographie",
        teachers: ["Pigeon C."],
        coefficient: 1,
        studentAverage: 18.2,
        classAverage: 17.78,
        classMin: 15.33,
        classMax: 20,
        appreciation:
          "Tres bons resultats et attitude exemplaire. Veiller a mieux organiser le travail a la maison.",
        evaluations: [
          {
            id: "hg-1",
            label: "Reperes",
            score: 19,
            maxScore: 20,
            recordedAt: "15/09",
          },
          {
            id: "hg-2",
            label: "Carte",
            score: 10,
            maxScore: 10,
            recordedAt: "03/11",
          },
          {
            id: "hg-3",
            label: "Lecon",
            score: 17,
            maxScore: 20,
            recordedAt: "24/11",
          },
        ],
      },
      {
        id: "anglais",
        subjectLabel: "Anglais LV1",
        teachers: ["Mme Emery L.", "Mme Assade S."],
        coefficient: 1,
        studentAverage: 19.75,
        classAverage: 18.18,
        classMin: 14.92,
        classMax: 20,
        appreciation: "Excellent trimestre.",
        evaluations: [
          {
            id: "en-1",
            label: "Vocabulary",
            score: 9.5,
            maxScore: 10,
            recordedAt: "08/09",
          },
          {
            id: "en-2",
            label: "Listening",
            score: 30,
            maxScore: 30,
            recordedAt: "21/10",
          },
          {
            id: "en-3",
            label: "Speaking",
            score: 10,
            maxScore: 10,
            recordedAt: "09/12",
          },
        ],
      },
      {
        id: "arts",
        subjectLabel: "Arts plastiques",
        teachers: ["Mme Vignacourt V."],
        coefficient: 1,
        studentAverage: 13,
        classAverage: 16.87,
        classMin: 13,
        classMax: 20,
        appreciation:
          "Trimestre correct. Il faut cependant poursuivre les efforts.",
        evaluations: [
          {
            id: "ar-1",
            label: "Projet 1",
            score: 6.5,
            maxScore: 10,
            recordedAt: "17/09",
          },
          {
            id: "ar-2",
            label: "Projet 2",
            score: 13,
            maxScore: 20,
            recordedAt: "19/11",
          },
        ],
      },
      {
        id: "musique",
        subjectLabel: "Education musicale",
        teachers: ["Mme Chartier E."],
        coefficient: 1,
        studentAverage: 18.75,
        classAverage: 18.46,
        classMin: 12,
        classMax: 20,
        appreciation: "Paul est actif et volontaire. Bon trimestre.",
        evaluations: [
          {
            id: "mu-1",
            label: "Rythme",
            score: 20,
            maxScore: 20,
            recordedAt: "10/10",
          },
          {
            id: "mu-2",
            label: "Chant",
            score: 17.5,
            maxScore: 20,
            recordedAt: "02/12",
          },
        ],
      },
      {
        id: "svt",
        subjectLabel: "Sciences vie et terre",
        teachers: ["Mme Barriere C."],
        coefficient: 1,
        studentAverage: 12.73,
        classAverage: 13.06,
        classMin: 7.67,
        classMax: 17.57,
        appreciation:
          "Ensemble correct. Pour progresser davantage, bien relire les activites et les consignes.",
        evaluations: [
          {
            id: "svt-1",
            label: "Controle 1",
            score: 2,
            maxScore: 10,
            weight: 0.5,
            recordedAt: "11/09",
          },
          {
            id: "svt-2",
            label: "Controle 2",
            score: 13.5,
            maxScore: 25,
            recordedAt: "14/10",
          },
          {
            id: "svt-3",
            label: "Controle 3",
            score: 16.5,
            maxScore: 20,
            recordedAt: "02/12",
          },
        ],
      },
    ],
  },
  {
    term: "TERM_2",
    label: "2eme Trimestre",
    councilLabel: "Conseil de classe de 6eme N3 le mardi 17 mars 2026 a 16:45",
    generatedAtLabel: "Moyennes calculees le mardi 10 mars a 23:03",
    generalAverage: {
      student: 15.93,
      class: 16.47,
      min: 13,
      max: 19.47,
    },
    subjects: [
      {
        id: "francais",
        subjectLabel: "Francais",
        teachers: ["M. Jamet P.", "Mme Lambert M."],
        coefficient: 1,
        studentAverage: 18,
        classAverage: 17.29,
        classMin: 12.86,
        classMax: 20,
        appreciation:
          "Des resultats solides et reguliers. Maintenir les efforts en production ecrite.",
        evaluations: [
          {
            id: "fr2-1",
            label: "Lecture",
            score: 19,
            maxScore: 20,
            recordedAt: "08/01",
          },
          {
            id: "fr2-2",
            label: "Orthographe",
            score: 17.5,
            maxScore: 20,
            recordedAt: "30/01",
          },
          {
            id: "fr2-3",
            label: "Expression",
            score: 18,
            maxScore: 20,
            weight: 0.5,
            recordedAt: "04/03",
          },
        ],
      },
      {
        id: "mathematiques",
        subjectLabel: "Mathematiques",
        teachers: ["M. Auberger C.", "M. Jacquier S."],
        coefficient: 1,
        studentAverage: 16.04,
        classAverage: 15.55,
        classMin: 6.1,
        classMax: 20,
        appreciation:
          "Bon trimestre dans l'ensemble. Quelques baisses d'attention sur les problemes complexes.",
        evaluations: [
          {
            id: "ma2-1",
            label: "Calcul",
            score: 30.5,
            maxScore: 40,
            weight: 2,
            recordedAt: "15/01",
          },
          {
            id: "ma2-2",
            label: "Geometrie",
            score: 14,
            maxScore: 20,
            recordedAt: "13/02",
          },
          {
            id: "ma2-3",
            label: "Resolution",
            score: 15.5,
            maxScore: 20,
            recordedAt: "05/03",
          },
          {
            id: "ma2-4",
            label: "Application",
            score: 19.4,
            maxScore: 20,
            weight: 2,
            recordedAt: "09/03",
          },
        ],
      },
      {
        id: "histoire",
        subjectLabel: "Histoire-geographie",
        teachers: ["Pigeon C."],
        coefficient: 1,
        studentAverage: 13.46,
        classAverage: 16.09,
        classMin: 12.7,
        classMax: 18.89,
        appreciation:
          "Le travail est serieux mais l'apprentissage des lecons doit etre plus regulier.",
        evaluations: [
          {
            id: "hg2-1",
            label: "Chapitre 1",
            score: 11,
            maxScore: 20,
            recordedAt: "09/01",
          },
          {
            id: "hg2-2",
            label: "Carte",
            score: 8.5,
            maxScore: 10,
            recordedAt: "29/01",
          },
          {
            id: "hg2-3",
            label: "Chapitre 2",
            score: 14.6,
            maxScore: 20,
            recordedAt: "20/02",
          },
          {
            id: "hg2-4",
            label: "DM",
            score: 3.5,
            maxScore: 5,
            recordedAt: "06/03",
          },
        ],
      },
      {
        id: "anglais",
        subjectLabel: "Anglais LV1",
        teachers: ["Mme Emery L.", "Mme Assade S."],
        coefficient: 1,
        studentAverage: 17.4,
        classAverage: 16.67,
        classMin: 12.7,
        classMax: 19.67,
        appreciation: "Bon trimestre, expression orale de qualite.",
        evaluations: [
          {
            id: "en2-1",
            label: "Vocabulary",
            score: 9,
            maxScore: 10,
            recordedAt: "14/01",
          },
          {
            id: "en2-2",
            label: "Listening",
            score: 31,
            maxScore: 40,
            recordedAt: "18/02",
          },
          {
            id: "en2-3",
            label: "Writing",
            score: 5,
            maxScore: 5,
            weight: 0.5,
            recordedAt: "03/03",
          },
        ],
      },
      {
        id: "arts",
        subjectLabel: "Arts plastiques",
        teachers: ["Mme Vignacourt V."],
        coefficient: 1,
        studentAverage: 13.5,
        classAverage: 16.9,
        classMin: 13.5,
        classMax: 20,
        appreciation:
          "Des productions appliquees mais une implication encore irreguliere.",
        evaluations: [
          {
            id: "ar2-1",
            label: "Projet 3",
            score: 13.5,
            maxScore: 20,
            recordedAt: "10/02",
          },
        ],
      },
      {
        id: "musique",
        subjectLabel: "Education musicale",
        teachers: ["Mme Chartier E."],
        coefficient: 1,
        studentAverage: 18,
        classAverage: 18.08,
        classMin: 13.5,
        classMax: 20,
        appreciation: "Participation active, tres bon esprit de groupe.",
        evaluations: [
          {
            id: "mu2-1",
            label: "Interpretation",
            score: 18,
            maxScore: 20,
            recordedAt: "26/02",
          },
        ],
      },
      {
        id: "svt",
        subjectLabel: "Sciences vie et terre",
        teachers: ["Mme Barriere C."],
        coefficient: 1,
        studentAverage: 15.13,
        classAverage: 14.66,
        classMin: 10.6,
        classMax: 18,
        appreciation:
          "Trimestre satisfaisant. Les efforts de methode portent leurs fruits.",
        evaluations: [
          {
            id: "svt2-1",
            label: "Controle 4",
            score: 15,
            maxScore: 20,
            recordedAt: "16/01",
          },
          {
            id: "svt2-2",
            label: "TP",
            score: 6,
            maxScore: 10,
            weight: 0.5,
            recordedAt: "06/02",
          },
          {
            id: "svt2-3",
            label: "Controle 5",
            score: 14,
            maxScore: 20,
            recordedAt: "03/03",
          },
          {
            id: "svt2-4",
            label: "DM",
            score: 12,
            maxScore: 15,
            weight: 0.5,
            recordedAt: "09/03",
          },
        ],
      },
    ],
  },
  {
    term: "TERM_3",
    label: "3eme Trimestre",
    councilLabel: "Conseil de classe a venir",
    generatedAtLabel: "Donnees de demonstration en attente de consolidation",
    generalAverage: {
      student: null,
      class: null,
      min: null,
      max: null,
    },
    subjects: [],
  },
];
